import numpy as np
from io import BytesIO

def generate_obj(img, scale_z=1.0):
    """
    تبدیل تصویر به یک فایل OBJ (شبکهٔ ارتفاعی)
    img: PIL Image (grayscale یا رنگی → تبدیل به خاکستری)
    scale_z: مقیاس ارتفاع (پیش‌فرض ۱)
    """
    # تبدیل به آرایه numpy و سپس به سیاه‌سفید
    gray = img.convert('L')
    width, height = gray.size
    # کاهش رزولوشن برای حجم مناسب (حداکثر ۱۰۰×۱۰۰)
    max_res = 100
    if width > max_res or height > max_res:
        ratio = min(max_res / width, max_res / height)
        new_w = int(width * ratio)
        new_h = int(height * ratio)
        gray = gray.resize((new_w, new_h), resample=3)  # BICUBIC
        width, height = new_w, new_h

    pixels = np.array(gray, dtype=np.float32)
    # نرمال‌سازی ارتفاع بین 0 تا scale_z
    if pixels.max() > 0:
        heights = (pixels / 255.0) * scale_z
    else:
        heights = np.zeros_like(pixels)

    # تولید رئوس
    vertices = []
    for y in range(height):
        for x in range(width):
            z = heights[y, x]
            vertices.append((x, y, z))

    # تولید وجه‌ها (دو مثلث برای هر چهارضلعی)
    faces = []
    for y in range(height - 1):
        for x in range(width - 1):
            i0 = y * width + x + 1          # OBJ شماره‌گذاری از ۱
            i1 = y * width + (x + 1) + 1
            i2 = (y + 1) * width + x + 1
            i3 = (y + 1) * width + (x + 1) + 1
            faces.append((i0, i1, i3))
            faces.append((i0, i3, i2))

    # ساخت رشته OBJ
    obj_lines = ["# Generated by Refrigitz Olympic"]
    for v in vertices:
        obj_lines.append(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}")
    for f in faces:
        obj_lines.append(f"f {f[0]} {f[1]} {f[2]}")

    obj_str = "\n".join(obj_lines)
    return obj_str.encode('utf-8')
